title: "Dave's Blog"
author: "Dave Lehman"
description: "I write about Ruby and Rails, mechanical keyboards (and macropads), 3D-printing, coffee roasting, and maybe more." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "dlehman@gmail.com"
twitter_username: "dlehman"
github_username: "dlehman"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

# theme: "minima"
remote_theme: pages-themes/minimal@v0.2.0
rss: rss
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
kramdown:
  syntax_highlighter_opts:
    disable: true
titles_from_headings:
  strip_title: true
  collections: true
defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
